spring:
  profiles:
    active: 
      - cat
      - ES
      - dev
datasource:
  username: ymlRin
  password: ymlRinoir98
  jdbcurl:  ymlsomeURL
  
---

spring:
  profiles: prod
  
datasource:
  username: ymlProd_Rin
  password: ymlProd_Rinoir98
  jdbcurl:  ymlProd_someURL